[theme]
# Primary accent color for your app.
primaryColor="#FF4B4B" # Um tom de vermelho vibrante (Streamlit default)

# Background color for the main content area.
backgroundColor="#FFFFFF" # Branco puro

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#F0F2F6" # Um cinza claro

# Color used for almost all text.
textColor="#262730" # Um cinza escuro para o texto

# Font family for the app. Options: "sans serif", "serif", "monospace".
# Use "sans serif" para uma leitura moderna e limpa.
font="sans serif"

# Set the overall theme for your app.
# Options: "light" or "dark".
base="light"

[browser]
title = "Treino de Discursivas"
